# http://travis-ci.org/#!/agschwender/pilbox
dist: trusty
sudo: required
language: python
python:
  - 3.6
env:
  - PYTHONPATH=$PYTHONPATH:$PWD
before_install:
  - sudo apt-get update
  - sudo apt-get install libjpeg8-dev libfreetype6-dev zlib1g-dev
  - sudo apt-get install libwebp-dev liblcms2-dev
  - sudo apt-get install python-numpy python-opencv python-pycurl
install:
  - pip install pep8==1.6.2 pyflakes==0.8.1
  - pip install -r requirements.txt
before_script:
  - pep8 --exclude=test pilbox
  - pyflakes pilbox/*.py
script:
  - coverage run -m pilbox.test.runtests
after_success:
  - coveralls
